name: Get project package version
inputs:
  file:
    description: path to .csproj
    required: true
  package:
    description: package name
    required: true
  xpath:
    description: XPath to version element
    required: false
    default: '//ItemGroup/PackageReference[@Include="\$1"]/@Version'
outputs:
  version:
    description: version of inputs.package retrieved from inputs.file
    value: ${{ steps.get.outputs.version }}
runs:
  using: composite
  steps:
  - id: get
    name: Get package ${{ inputs.package }} version from ${{ inputs.file }}
    shell: bash
    run: |-
      csproj-dependency-version get --package ${{ inputs.package }} --xpath ${{ inputs.xpath }} ${{ inputs.file }}
      echo "version=$(csproj-dependency-version get --package ${{ inputs.package }} --xpath ${{ inputs.xpath }} ${{ inputs.file }})" >> $GITHUB_OUTPUT
  - shell: bash
    run: |-
      echo ${{ steps.get.outputs.version }}
