name: Publish package (NPM)

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        description: 'The NPM access token passed from the caller workflow'
        required: true

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Update
        run: |
          git fetch --all
          git pull

      - name: Install dependencies
        run: npm install

      - name: Create package
        id: pack
        run: |
          npm pack
          echo "::set-output name=package::`ls *.tgz`"
      - name: Show package
        run: |
          ls ${{ steps.pack.outputs.package }}
          tar tvf ${{ steps.pack.outputs.package }}

      - name: Create release
        uses: actions/github-script@v6
        id: create_release
        #env:
        #  GITHUB_TOKEN: ${{ github.TOKEN }}
        with:
        #  github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const release = github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ inputs.tag }}",
              release_name: "Release ${{ inputs.tag }}",
              prerelease: false,
              draft: false,
              body: '@CHANGELOG.md',
            });
            console.log(release);
            return release;

      ##- name: Upload release artifacts
      ##  uses: actions/github-script@v6
      ##  env:
      ##    GITHUB_TOKEN: ${{ github.TOKEN }}
      ##  with:
      ##    github-token: ${{secrets.GITHUB_TOKEN}}
      ##    script: |
      ##      const asset = github.rest.repos.uploadReleaseAsset({
      ##        owner: context.repo.owner,
      ##        repo: context.repo.repo,
      ##        release_id: context.steps.create_release.outputs.id,
      ##        name: context.steps.pack.outputs.package,
      ##        data: context.steps.pack.outputs.package,
      ##      });


##  publish-to-github-registry:
##    needs: release
##    runs-on: ubuntu-latest
##    permissions:
##      contents: read
##      packages: write
##    steps:
##      - uses: actions/checkout@v2
##      - uses: actions/setup-node@v2
##        with:
##          node-version: 16
##          registry-url: https://npm.pkg.github.com/
##          scope: '@kagekirin'

##      - name: Publish to GitHub NPM Registry
##        run: npm publish --access public --verbose
##        env:
##          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


##  publish-to-npmjs-registry:
##    needs: release
##    runs-on: ubuntu-latest
##    permissions:
##      contents: read
##      packages: write
##    steps:
##      - uses: actions/checkout@v2
##      - uses: actions/setup-node@v2
##        with:
##          node-version: 16
##          registry-url: https://registry.npmjs.org/
##          scope: '@kagekirin'

##      - name: Patch package.json
##        run: |
##          sed -i -e "s|npm.pkg.github.com/@kagekirin|registry.npmjs.org|g" package.json
##          cat package.json

##      - name: Publish to NPM.JS Registry
##        run: npm publish --access public --verbose
##        env:
##          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
